name: Build Zed for Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Включение длинных путей в Windows
        run: |
          reg add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f
        shell: cmd

      - name: Настройка Git для поддержки длинных путей
        run: git config --global core.longpaths true

      - name: Уменьшение длины пути для Cargo и Git
        run: |
          echo "CARGO_HOME=C:\cargo" >> $GITHUB_ENV
          echo "GIT_DIR=C:\git" >> $GITHUB_ENV

      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Установка зависимостей (CMake, MSVC)
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install visualstudio2022buildtools --yes --package-parameters="--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre --add Microsoft.VisualStudio.Component.Windows11SDK.26100 --includeRecommended --includeOptional --quiet --norestart"
          choco install visualstudio2022-workload-vctools -y
        shell: cmd

      - name: Компиляция Zed (Release)
        run: cargo build --release

      - name: Запуск тестов
        run: cargo test --workspace

      - name: Сохранение артефактов
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-build
          path: target/release/
