name: Build Zed for Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Установка зависимостей (CMake, MSVC)
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install visualstudio2022buildtools -y
          choco install visualstudio2022-workload-vctools -y
        shell: bash

      - name: Установка Windows SDK через Visual Studio Installer
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" ^
          modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\BuildTools" ^
          --add Microsoft.VisualStudio.Component.Windows10SDK.20348 ^
          --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 ^
          --add Microsoft.VisualStudio.Component.Windows11SDK.26100
        shell: cmd

      - name: Компиляция Zed (Release)
        run: cargo build --release

      - name: Запуск тестов
        run: cargo test --workspace

      - name: Сохранение артефактов
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-build
          path: target/release/
